# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Publish to PyPi

on:
  push:
    branches: [ "!*" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing Dependencies
      run: python -m pip install --upgrade build flake8
    - name: Verify git tag matches setup.py version
      run: |
        SETUP_PY_VERSION=$(python3 setup.py --version)
        TAG_VERSION=${GITHUB_REF#*tags/v}
        echo $SETUP_PY_VERSION to $TAG_VERSION from $GITHUB_REF
        if [[ $SETUP_PY_VERSION != $TAG_VERSION ]]; then
          echo setup.py version does not match version tag.
          echo setup.py version tag should have the format 0.0.1.
          echo git version tag should have the format v0.1.1
          exit 1
        else
          echo git tag matches setup.py
        fi
    - name: flake8 checks
      run: flake8 .  --count --show-source --statistics
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
